### PR TITLE
Update for Ember 2.0 Deprecation

### PR DESCRIPTION
**Pull request by jhr007**
I was getting a WSOD of death, with an error saying Ember.default.View can't be found. 

Grepping around, and found another package(qunit*) that used `if (Ember.View)` to wrap their code. 

Cheers

### CODE REVIEW

**Comment by jhr007** [comment]
I think Travis failed because of a network issue. 
Anyway to manually rerun?

**Comment by mike-north** [comment]
kicked travis for you

**Comment by mike-north** [comment]
looks like the tests are legitimately failing. I would try to run 

```sh
ember try ember-release
```
locally and see if it passes

**Comment by jhr007** [comment]
I think tests are failing cause of Ember 2.0.1 is the latest release ... Most of them are failing with: 
`Attempting to register an unknown factory: controller:object`

Here's what I found so far... 

`Pikaday had this issue... thanks to google indexing their commits :D `
https://travis-ci.org/edgycircle/ember-pikaday/jobs/71928764
`but was fixed on this build: `
https://travis-ci.org/edgycircle/ember-pikaday/builds/77644542
`using this commit...  `
https://github.com/edgycircle/ember-pikaday/commit/bb64a590756bdb3393332304fc362a591f6f4c7b

but our build isn't failing giving js hint errors, or I'm not seeing them near the top.

**Pull request closed without merging**
